### ISSUE TITLE
Non-clickable item in the cart

### ISSUE THREAD

**Issue by Diana-Smolnikova** [Sunagatov/Iced-Latte-Frontend#145]
Priority: Medium

Pre-conditions:
1. User logged in.
2. Product add to cart

Steps:
1. Click on the product item 

ER: Opening product page 
FR: Item non-clickable
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/0d34b79d-6f93-4234-bde0-5a38d325b6a9)

**Comment by ilsinyakov** [comment]
Requirements:
US5.12 | As a customer I want to go to the product page by clicking on product name or image

Now product name is not clickable
