### ISSUE TITLE
Hover effect on add to cart button

### ISSUE THREAD

**Issue by Diana-Smolnikova** [Sunagatov/Iced-Latte-Frontend#146]
Statec og button

Need to remove hover effect from add to cart button in state when at least 1 item was previously added to cart.

![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/15b6ad35-1ee0-449d-97c2-da86f21d8f8c)

**Comment by ilsinyakov** [comment]
Tested
Fixed
