### ISSUE TITLE
Text inconsistency. Should be "confirm registration" instead of "confirm password"

### ISSUE THREAD

**Issue by Diana-Smolnikova** [Sunagatov/Iced-Latte-Frontend#147]
Priority: Low

Pre-conditions:
User is not registered

Steps:

1. Navigate to the registration page.  https://iced-latte.uk/auth/registration
2. Fill out the registration form
3. Click the "Register" button.

ER: The user is presented with a message that accurately reflects the current step in the registration process.

AR: The user  observe   “Confirm Password,” which is misleading and does not align with the expected sequence of registration steps. This text suggests a different action than what should logically follow the initial registration submission, potentially causing confusion.

![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/8396c4d7-b784-45b3-9508-18c426c720e0)

**Comment by ilsinyakov** [comment]
Tested.
Approved.

**Comment by Diana-Smolnikova** [comment]
Tested
Approved
