### ISSUE TITLE
(SHOPPING CART PAGE) Subtotal in cart does not change after increase/decrease items

### ISSUE THREAD

**Issue by Diana-Smolnikova** [Sunagatov/Iced-Latte-Frontend#148]
Priority: Higth

Pre-conditions:

Steps:
1.Navigate to home page https://iced-latte.uk/ .
2.Chose randomly any product and add to the cart.
3.Navigate to cart and decrease/ increase the product.

ER: Subtotal should change accordingly in moment increasing/decreasing.

AR: Subtotal change only after refresh page.

https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/fae91eca-1687-47c2-ba5c-a6cbe07dbc03

**Comment by iakivpekarskyi** [comment]
Somebody has fixed it already. In the current version as of 29.04.2024 the subtotal is being updated.

**Comment by iakivpekarskyi** [comment]
I couldn't find the solution.

**Comment by ilsinyakov** [comment]
Tested
Fixed
Test: UI/test_shopping_cart.py
