### ISSUE TITLE
Button of dropdown list "Sort by" is displayed on the Login & Registration Pages

### ISSUE THREAD

**Issue by ilsinyakov** [Sunagatov/Iced-Latte-Frontend#154]
**Pre-condition**:
User is not logged in

**Step**:
1. Open Login Page: https://iced-latte.uk/auth/login
2. Go to Registration Page: https://iced-latte.uk/auth/registration

**ER**: Button of dropdown list "Sort by" is not displayed on the Login & Registration Pages

**FR**: Button of dropdown list "Sort by" is displayed on the Login & Registration Pages

![2024-04-16 082012](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/f77b60b5-7775-4de2-9f68-bd7e0557f832)
![2024-04-16 082944](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/49bbd532-d1a7-4a17-8879-384f4ae06337)

**Comment by Lightness322** [comment]
Fixed: https://github.com/Sunagatov/Iced-Latte-Frontend/pull/142

**Comment by ilsinyakov** [comment]
Approved
test: https://github.com/Sunagatov/Iced-Latte-QA/blob/development/UI/test_dropdawn_not_present.py

**Comment by ilsinyakov** [comment]
fixed
