### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) Weights of the products is not equal on Main Page, Product Page and on Favorites Page

### ISSUE THREAD

**Issue by ilsinyakov** [Sunagatov/Iced-Latte-Frontend#156]
**Pre-conditions**:
Some products added to Favorites

**Steps**:
1. Сompare weights on Main Page, Product Page and on Favorites Page

**ER**: weights is equal

**AR**: weights is not equal 

![2024-04-16 094115](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/823a8374-d9fc-4b0e-8bb2-4a4641ba87c5)

![2024-04-16 094146](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/4cc6a87d-08d8-4f16-997c-219c89c34ea0)

![2024-04-16 094216](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/d20c946b-161a-46f3-8d19-23f028b33f5e)

![2024-04-16 094250](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/140279745/74cdb4fc-3eba-4da6-b2c4-14bc05d83e2d)

**Comment by Sunagatov** [comment]
@ilsinyakov I am going to close the bug as we will remove the attribute weighs everywhere on the website.

We have already removed it on the product card on the main page and the shopping cart web page.

We need to remove it on the product page and the favourite page. I will attach the new github issues links to this issue for your attention.
