### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) Display Issue: Misaligned "Add to Cart" Button on the Main Page

### ISSUE THREAD

**Issue by Diana-Smolnikova** [Sunagatov/Iced-Latte-Frontend#159]
Description: On the main page, the "Add to Cart" button is displayed incorrectly due to misalignment.

Environment: Chrome, FF, Safari
Steps:
1. Open main page https://iced-latte.uk/
2. Scroll to the end (photo 1)

Environment: Mobile, safari
Steps:
1. Open main page https://iced-latte.uk/
2. Scroll to the "Сhai Latte" (photo 2)
3. Scroll to the end (photo 3)

![Снимок экрана 2024-04-17 в 17 43 05](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/4d6da5e2-2608-427d-a02b-3ffcabb30846) 
![IMG_3737](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/ee009a34-e8c9-4e3d-bdaa-d7a6e71e5b2c)
![IMG_3738](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/164781898/70380d33-c231-44de-8d21-93cd048a348f)

**Comment by Lightness322** [comment]
Fixed, test please
PR: https://github.com/Sunagatov/Iced-Latte-Frontend/pull/173

**Comment by Diana-Smolnikova** [comment]
Tested
Approved
