### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) Product Card (Average Rating + Reviews Count)

### ISSUE THREAD

**Issue by Sunagatov** [Sunagatov/Iced-Latte-Frontend#179]
**Before:**
Now all the values you see in the product card on the website are hardcoded.

**After:**
In the product card we need to show the rating and the number of reviews that come from the backend REST API as json as follows:
1) If backend returns product with the average rating of the product as 4,8  and 13 as the number of reviews then on the product card is should look like that 🌟**4,8 (13)**.
![Screenshot 2024-04-28 at 11 33 25 am](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/23553019/026387d6-5a3e-4eb7-813f-c6a54516f52d)

2) If backend returns product with the average rating of the product as null or 0  and the number of reviews as null or 0 then on the product card is should look like that **No rating**.
![Screenshot 2024-04-28 at 11 35 13 am](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/23553019/471bdae3-5f8c-4954-9917-27a29a4226a8)

**Comment by ilsinyakov** [comment]
Tested
Approved
