### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) Load list of brands and list of sellers from the backend

### ISSUE THREAD

**Issue by Sunagatov** [Sunagatov/Iced-Latte-Frontend#181]
**Before:**
Now List of brands and list of sellers are just hardcoded on the frontend side.

![Screenshot 2024-04-28 at 11 51 43 am](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/23553019/9df3062c-3d0e-4a55-b010-5614be59e29d)

**After:**
You need to load list of brands and list of sellers from the backend from the appropriate REST API. Check Swagger Docs to find the  API.

**Comment by ilsinyakov** [comment]
Test: UI/test_main_page.py
