### ISSUE TITLE
(PRODUCT PAGE) Statistics with ratings disappears

### ISSUE THREAD

**Issue by Lightness322** [Sunagatov/Iced-Latte-Frontend#197]
**Pre-conditions:**

1. Product has at least 1 review
2. Go to product page

**Steps:**

1. Select a filter by rating that is not present among the reviews

**ER:**
Empty review list and statistics with ratings doesn't disappear

**AR:**
Empty review list but statistics with ratings disappears

**Comment by ilsinyakov** [comment]
Tested  
Fixed  
The test is not currently developed
