### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) Filter Reset and Badge Display

### ISSUE THREAD

**Issue by anksuunamun** [Sunagatov/Iced-Latte-Frontend#206]
1. Implement a reset of all filters via a "Reset" button.
2. Set up the display of badges for selected filters according to what is chosen in the sidebar.

![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/8d48bdf4-278e-4c3d-be8b-e1df40e5515a)

![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/394c5e70-ea92-48b7-8693-8bd687139f6f)

**Comment by ilsinyakov** [comment]
Tested  
The test is not currently developed
